In [17]:
#Importing of data
import pandas as pd
df = pd.read_csv('customer_shopping_behavior.csv')

In [19]:
#Checking first few lines of data (default is 5)
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [21]:
#Checking all the columns and its data type
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [23]:
#Summary Statistics
df.describe() #By default it will give summary stats for only numerical columns
#If you want to include everything in summary stats use: df.describe(include='all')

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [25]:
#Checking for any null values
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [27]:
#Filling in the null values using the median because it is robust to the outliers unlike mean.
#For this case we will be grouping the review rating as per the product category in order to avoid bias
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [29]:
#Checking for null values again
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [39]:
#Replacing your column name to snake casing.
#Snake casing it transforming you column name in all lowercase with underscores.
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [41]:
#Checking column names
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [43]:
#Creating a new column called age_group
labels = ['Young Adult','Adult','Middle-aged','Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels) #qcut splits the ages into four equal-sized groups 
                                                           #based on the data distribution and assigns the labels we defined.

In [45]:
#Checking specific column data
df[['age', 'age_group']].head(10) #Specifing the number of data lines that you want to check

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [51]:
#Creating a column named purchase_frequency_days
#The data in frequency of purchase column is in text form, we will be convertong it into numerical form
#Creating a dictionary called frequency mapping that maps each textual frequency to the equivalent no. of days.

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [53]:
df[['purchase_frequency_days', 'frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [55]:
df[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [57]:
#Checking if the data of both the columns are same or not
#If true then yes and if false then no.

(df['discount_applied'] == df['promo_code_used']).all()

True

In [61]:
#Dropping the column named promo_code_used

df = df.drop('promo_code_used', axis=1)

In [63]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [65]:
#Installing sqlalchemy and pymysql
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\adhya\anaconda3\lib\site-packages (2.0.30)Note: you may need to restart the kernel to use updated packages.

Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\adhya\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\adhya\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
   ---------------------------------------- 0.0/45.7 kB ? eta -:--:--
   ---------------------------------------- 0.0/45.7 kB ? eta -:--:--
   -------- ------------------------------- 10.2/45.7 kB ? eta -:--:--
   -------------------------- ------------- 30.7/45.7 kB 262.6 kB/s eta 0:00:01
   ---------------------------------------- 45.7/45.7 kB 322.5 kB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

In [87]:
#Importing the cleaned data into SQL database
import pymysql

try:
    conn = pymysql.connect(
        host="localhost",
        user="root",
        password="PASSWORD"
    )
    print("SUCCESS - Password is correct")
    conn.close()

except Exception as e:
    print("ERROR:")
    print(e)

SUCCESS - Password is correct

In [101]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:PASSWORD@localhost:3306/customer_behavior_analysis"
)

In [103]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = quote_plus("PASSWORD")

engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost:3306/customer_behavior_analysis"
)

In [105]:
#Connecting python to MySQL Workbench
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("SELECT 1"))
    print("Connected successfully!")

Connected successfully!

In [109]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365

In [111]:
df.to_sql(
    name='customer_data',
    con=engine,
    if_exists='replace',
    index=False
)

print("Data uploaded successfully!")

Data uploaded successfully!